practice-for-ch-js-ajax-twitter-long-practice-main 2/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get "feed", to: "tweets#feed", as: :feed
  resource :session, only: [:create, :destroy, :new]
  resources :tweets, only: [:create,:index]
  resources :users, only: [:create, :new, :show] do
    get "search", on: :collection
    resource :follow, only: [:create, :destroy]
  end

  root to: redirect("/feed")
end

practice-for-ch-js-ajax-twitter-long-practice-main 2/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

practice-for-ch-js-ajax-twitter-long-practice-main 2/app/models/follow.rb
class Follow < ApplicationRecord
  validates :follower, uniqueness: { scope: :following }

  belongs_to :follower, 
    class_name: :User
  belongs_to :following, 
    class_name: :User
end

practice-for-ch-js-ajax-twitter-long-practice-main 2/app/models/tweet.rb
class Tweet < ApplicationRecord
  validates :body, presence: true, length: { maximum: 280 }

  belongs_to :author, 
    foreign_key: :author_id,
    class_name: :User
  belongs_to :mentioned_user,
    foreign_key: :mentioned_user_id,
    class_name: :User,
    optional: true
end

practice-for-ch-js-ajax-twitter-long-practice-main 2/app/models/user.rb
class User < ApplicationRecord
  attr_reader :password

  validates :username, :password_digest, :session_token, presence: true
  validates :username, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }

  # I'm the one users are *following*, so they are my *followers*
  has_many :in_follows,
    foreign_key: :following_id,
    class_name: :Follow
  has_many :followers,
    through: :in_follows,
    source: :follower

  # I'm the *follower*, so these are the users I'm *following*
  has_many :out_follows,
    foreign_key: :follower_id,
    class_name: :Follow
  has_many :following,
    through: :out_follows,
    source: :following

  has_many :tweets, 
    foreign_key: :author_id,
    dependent: :destroy
  has_many :followed_tweets,
    through: :following,
    source: :tweets

  after_initialize :ensure_session_token

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    user && user.is_password?(password) ? user : nil
  end

  def self.generate_session_token
    loop do
      token = SecureRandom.base64
      break token unless User.exists?(session_token: token)
    end
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_session_token!
    self.update!(session_token: User.generate_session_token)
    self.session_token
  end

  def page_of_tweets(type:, offset: 0, limit: nil)
    tweet_source = 
      case type
      when "feed", :feed then followed_tweets
      when "profile", :profile then tweets
      else 
        raise ArgumentError.new("Invalid type '#{type}' provided to User#page_of_tweets")
      end
    
    tweet_source
      .limit(limit || 10)
      .offset(offset)
      .order(created_at: :desc)
      .includes(:author, :mentioned_user)
  end

  def follows?(user)
    following.any? { |u| u == user }
  end

  private

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end
end

practice-for-ch-js-ajax-twitter-long-practice-main 2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  before_action -> { params.deep_transform_keys!(&:underscore) }

  def current_user
    return nil if session[:session_token].nil?
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def log_in!(user)
    session[:session_token] = user.reset_session_token!
  end

  def log_out!
    current_user.reset_session_token! if current_user
    session[:session_token] = nil
  end

  def require_logged_in!
    redirect_to new_session_url if current_user.nil?
  end

  def require_not_logged_in!
    redirect_to feed_url unless current_user.nil?
  end
end

practice-for-ch-js-ajax-twitter-long-practice-main 2/app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  before_action :require_logged_in!

  def create
    # simulate latency
    sleep(1)

    follow = current_user.out_follows.create!(following_id: params[:user_id])

    respond_to do |format|
      format.html { redirect_to request.referrer }
      format.json { render json: current_user.slice(:id, :username) }
    end
  end

  def destroy
    # simulate latency
    sleep(1)

    follow = current_user.out_follows.find_by(following_id: params[:user_id])
    follow.destroy!

    respond_to do |format|
      # Set redirect status to `:see_other` (303) to force a `GET` request. 
      # Otherwise, some browsers will keep the method of the redirect as 
      # `DELETE`.
      # See https://api.rubyonrails.org/classes/ActionController/Redirecting.html#method-i-redirect_to
      format.html { redirect_to request.referrer, status: :see_other }
      format.json { render json: current_user.slice(:id) }
    end
  end
end

practice-for-ch-js-ajax-twitter-long-practice-main 2/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :require_not_logged_in!, only: [:create, :new]
  before_action :require_logged_in!, only: [:destroy]

  def create
    if params[:demo].present?
      @user = User.find(params[:demo])
    else
      @user = User.find_by_credentials(
        params[:user][:username],
        params[:user][:password]
      )
    end

    if @user
      log_in!(@user)
      redirect_to feed_url
    else
      flash.now[:errors] = ['Invalid credentials']
      render :new
    end
  end

  def destroy
    log_out!
    
    redirect_to new_session_url
  end

  def new
    render :new
  end
end

practice-for-ch-js-ajax-twitter-long-practice-main 2/app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :require_logged_in!

  def feed
    @tweets = current_user.page_of_tweets(type: :feed, limit: params[:limit])
    render :feed
  end

  def index
    # simulate latency
    sleep(1)
    @tweets = current_user.page_of_tweets(type: :feed, offset: params[:limit])
    render :index
  end

  def create
    # simulate latency
    sleep(1)

    @tweet = current_user.tweets.build(tweet_params)
    if @tweet.save
      respond_to do |format|
        format.html { redirect_to user_url(current_user) }
        # Your code here
      end
    else
      errors = @tweet.errors.full_messages
      respond_to do |format|
        format.html do 
          flash[:errors] = errors
          redirect_to request.referrer 
        end
        # Your code here
      end
    end
  end

  private
  
  def tweet_params
    params.require(:tweet).permit(:body, :mentioned_user_id)
  end
end

practice-for-ch-js-ajax-twitter-long-practice-main 2/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_not_logged_in!, only: [:create, :new]
  before_action :require_logged_in!, only: [:show, :search]

  def create
    @user = User.new(user_params)

    if @user.save
      log_in!(@user)
      redirect_to feed_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def new
    @user = User.new # dummy user (view expects @user to be defined)
    render :new
  end

  def show
    @user = User.includes(tweets: :mentioned_user).find(params[:id])
    render :show
  end

  def search
    # simulate latency
    sleep(0.5)

    if params[:query].present?
      @users = User.where("username iLIKE ?", params[:query] + "%")
    else
      @users = User.none
    end

    render :search
  end

  protected
  
  def user_params
    self.params.require(:user).permit(:username, :password)
  end
end

practice-for-ch-js-ajax-twitter-long-practice-main 2/app/helpers/application_helper.rb
module ApplicationHelper
end

practice-for-ch-js-ajax-twitter-long-practice-main 2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ajax Twitter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <style>
      @import url("https://fonts.googleapis.com/css?family=Fredoka+One|Roboto");
    </style>

    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "application", defer: true %>
  </head>

  <body>
    <header>
      <nav class="main-nav">
        <a href="/">
          <h1 class="logo">
            <span class="tiny">AJAX</span>Twitter
          </h1>
        </a>
        <ul class="links">
          <% if current_user %>
            <li><a href="<%= feed_url %>">Feed</a></li>
            <li><a href="<%= search_users_url %>">User Search</a></li>
            <li><a href="<%= user_url(current_user) %>">Profile</a></li>
            <li>
              <form class="button-form" action="/session" method="POST">
                <input type="hidden" name="_method" value="DELETE">
                <%= render "shared/auth_token" %>
                <button type="submit">Log out!</button>
              </form>
            </li>
          <% else %>
            <li><a href="<%= new_session_url %>">Log in</a></li>
            <li><a href="<%= new_user_url %>">Sign up</a></li>
          <% end %>
        </ul>
      </nav>
    </header>

    <main>
      <%= yield %>
    </main>
  </body>
</html>

practice-for-ch-js-ajax-twitter-long-practice-main 2/app/views/shared/_auth_token.html.erb
<input
  type="hidden"
  name="authenticity_token"
  value="<%= form_authenticity_token %>"
>

practice-for-ch-js-ajax-twitter-long-practice-main 2/app/views/shared/_errors.html.erb
<ul class="errors">
  <% if flash[:errors]%>
    <% flash[:errors].each do |err_msg| %>
      <li><%= err_msg %></li>
    <% end %>
  <% end %>
</ul>

practice-for-ch-js-ajax-twitter-long-practice-main 2/app/views/tweets/_form.html.erb
<form 
  class="simple-form tweet-compose" 
  action="<%= tweets_url %>"
  method="POST"
>
  <%= render 'shared/errors' %>
  <%= render 'shared/auth_token' %>

  <div class="tweet-body field">
    <textarea 
      id="tweet-textarea" 
      name="tweet[body]" 
      placeholder="What's on your mind?"
      required
    ></textarea>
    <span class="chars-remaining"></span>
  </div>

  <div class="mentioned-user">
    <label for="tweet[mentioned_user_id]">Mention User: </label>
    <select name="tweet[mentioned_user_id]">
      <option value="">
        ---None---
      </option>
      <% User.where.not(id: current_user.id).each_with_index do |user, idx| %>
        <option value="<%= user.id %>">
          <%= user.username %>
        </option>
      <% end %>
    </select>
  </div>

  <div class="tweet-actions">
    <button type="submit">Post Tweet!</button>
  </div>
</form>

practice-for-ch-js-ajax-twitter-long-practice-main 2/app/views/tweets/_infinite_tweets.html.erb
<div class="infinite-tweets" data-type=<%= type %>>
  <% if tweets.empty? %>
    <p>No tweets... yet!</p>
  <% end %>

  <ul class="tweets">
    <% tweets.each do |tweet| %>
      <li><%= render "tweets/tweet", tweet: tweet %></li>
    <% end %>
  </ul>

  <form>
    <input 
      type="hidden" 
      name="limit" 
      value=<%= (params[:limit] || 10).to_i + 10 %>
    >
    <button class="fetch-tweets-btn">Fetch more tweets!</button>
  </form>
</div>

practice-for-ch-js-ajax-twitter-long-practice-main 2/app/views/tweets/_tweet.html.erb
<div class="tweet">
  <h3 class="author">
    <a href="<%= user_url(tweet.author) %>">
      @<%= tweet.author.username %>
    </a>
  </h3>

  <span class="created-at">
    <%= tweet.created_at.getlocal.to_date.to_fs(:long) %>
  </span>

  <p><%= tweet.body %></p>

  <% if tweet.mentioned_user_id.present? %>    
    <div class="mentioned-user">
      Mentions:
      <a href="<%= user_url(tweet.mentioned_user) %>">
        @<%= tweet.mentioned_user.username %>
      </a>
    </div>
  <% end %>  
</div>

practice-for-ch-js-ajax-twitter-long-practice-main 2/app/views/tweets/feed.html.erb
<h2 class="page-header">Your Feed!</h2>

<%= render "tweets/form" %>
<%= render "tweets/infinite_tweets", 
  tweets: @tweets, type: "feed"
%>

practice-for-ch-js-ajax-twitter-long-practice-main 2/app/views/users/_follow_toggle.html.erb
<% is_following = current_user.follows?(user) %>

<form action="<%= user_follow_url(user) %>" method="POST">
  <%= render "shared/auth_token" %>

  <% if is_following %>
    <input type="hidden" name="_method" value="DELETE">
  <% end %>
  
  <button
    class="follow-toggle"
    data-user-id="<%= user.id %>"
    data-follow-state="<%= is_following ? "followed" : "unfollowed" %>"
  >
    <%= is_following ? "Unfollow!" : "Follow!" %>
  </button>
</form>

practice-for-ch-js-ajax-twitter-long-practice-main 2/app/views/users/new.html.erb
<h2 class="page-header">Sign up!</h2>

<%= render 'shared/errors' %>

<form class="simple-form" action="/users" method="POST">
  <%= render 'shared/auth_token' %>

  <div class="field">
    <label for="user_username">Username</label>
    <input
      type="text"
      name="user[username]"
      id="user_username"
      value="<%= @user.username %>"
      required
    >
  </div>

  <div class="field">
    <label for="user_password">Password</label>
    <input 
      type="password" 
      name="user[password]" 
      id="user_password"
      required
    >
  </div>

  <button type="submit">Create User!</button>

  <a href="<%= new_session_url %>">Already have an account? Log in!</a>
</form>

practice-for-ch-js-ajax-twitter-long-practice-main 2/app/views/users/search.html.erb
<h2 class="page-header">Search!</h2>

<div class="users-search">
  <form class="simple-form search-form" action="<%= search_users_url %>">
    <input 
      type="text" 
      name="query"
      autocomplete="off"
      placeholder="Enter a username"
      autofocus
    >
    <button type="submit" class="search-button">Search!</button>
    <span class="loading-indicator"></span>
  </form>

  <ul class="users">
    <% @users.each do |user| %>
      <li>
        <a href="<%= user_url(user) %>">
          @<%= user.username %>
        </a>
        <%= render "users/follow_toggle", user: user %>
      </li>
    <% end %>
  </ul>
</div>

practice-for-ch-js-ajax-twitter-long-practice-main 2/app/views/users/show.html.erb
<h2 class="page-header"><%= @user.username %></h2>

<div class="user-detail">
  <% unless current_user == @user %>
    <%= render "users/follow_toggle", user: @user %>
  <% end %>

  <article class="left-half">
    <% if @user == current_user%>  
      <%= render "tweets/form" %>
    <% end %>

    <%= render "tweets/infinite_tweets", 
      tweets: @user.page_of_tweets(type: :profile, limit: params[:limit])
    %>
  </article>

  <aside class="right-half">
    <ul class="users followers">Followers
      <% if @user.followers.count == 0 %>
        <p> No followers... yet!</p>
      <% else %>
        <% @user.followers.each do |follower| %>
          <li>
            <a href="<%= user_url(follower) %>">
              @<%= follower.username %>
            </a>
          </li>
        <% end %>
      <% end %>
    </ul>

    <ul class="users">Following
      <% if @user.following.count == 0 %>
        <p> You're not following anyone... yet!</p>
      <% else %>
        <% @user.following.each do |user| %>
          <li>
            <a href="<%= user_url(user) %>">
              @<%= user.username %>
            </a>
          </li>
        <% end %>
      <% end %>
    </ul>
  </aside>
</div>